In [1]:
from google.colab import drive #importamos google drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd "/content/drive/My Drive/Colab Notebooks/dl-pytorch/datasets"
!ls

/content/drive/My Drive/Colab Notebooks/dl-pytorch/datasets
64x64_SIGNS  64x64_SIGNS.zip


In [3]:
!unzip 64x64_SIGNS.zip #discomprimimos

Archive:  64x64_SIGNS.zip
replace 64x64_SIGNS/.DS_Store? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: 64x64_SIGNS/.DS_Store   
  inflating: 64x64_SIGNS/train_signs/5_IMG_5556.jpg  
  inflating: 64x64_SIGNS/train_signs/3_IMG_6138.jpg  
  inflating: 64x64_SIGNS/train_signs/3_IMG_6104.jpg  
  inflating: 64x64_SIGNS/train_signs/5_IMG_5595.jpg  
  inflating: 64x64_SIGNS/train_signs/5_IMG_5581.jpg  
  inflating: 64x64_SIGNS/train_signs/1_IMG_4495.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5357.jpg  
  inflating: 64x64_SIGNS/train_signs/2_IMG_4648.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5343.jpg  
  inflating: 64x64_SIGNS/train_signs/2_IMG_4660.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5419.jpg  
  inflating: 64x64_SIGNS/train_signs/1_IMG_4456.jpg  
  inflating: 64x64_SIGNS/train_signs/4_IMG_5394.jpg  
  inflating: 64x64_SIGNS/train_signs/1_IMG_4442.jpg  
  inflating: 64x64_SIGNS/train_signs/5_IMG_5620.jpg  
  inflating: 64x64_SIGNS/train_signs/2_IMG_4728.jpg  
 

In [15]:
import sys   #importamos el modelos 
course_path = '/content/drive/My Drive/Colab Notebooks/dl-pytorch' #le damos una ruta (path de la carpeta pythorch actual)

sys.path.append(course_path) #que la recuerde siempre 

In [16]:
import plot_helpers #vemos que podemos importat las librerias para las imágenes
dir(plot_helpers) #vemos las cosas que tienen adentro la libreria

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'french',
 'imshow',
 'io',
 'np',
 'plot_cube',
 'plot_rgb_image',
 'plt',
 'torch',
 'visualize_model']

---
# TENSORES
---

![texto alternativo](https://i.imgur.com/21Ln3BP.png)

In [17]:
import torch
torch.__version__

'1.7.0+cu101'

In [18]:
A = torch.randn((8,3,5))
A.size()

torch.Size([8, 3, 5])

In [19]:
A.size() == (8,3,5)

True

Accediendo a valores del tensor

In [20]:
A[0][0][0]

tensor(-1.0658)

In [21]:
A[0,:,0]   #una columna con slice
A[0,0,:]

tensor([-1.0658, -2.1005, -1.3542, -0.2442,  0.5386])

In [22]:
A[0,0,:]   #una columna con slice igual que las listas

tensor([-1.0658, -2.1005, -1.3542, -0.2442,  0.5386])

In [23]:
C = torch.zeros((5,5))
C.dtype

torch.float32

In [24]:
D = torch.randint(2,(5,5))   #El 2 me indica que solo serán 0 o 1, (5,5) es el tamaño
D

tensor([[1, 1, 1, 1, 1],
        [0, 0, 0, 1, 0],
        [1, 0, 1, 1, 1],
        [1, 1, 0, 0, 1],
        [1, 0, 1, 0, 0]])

In [25]:
D.dtype # Observese que es tensor con valores enteros, diferente a C que es flotante

torch.int64

Observemos a la hora de sumar tensores

In [26]:
C+D

tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 0.],
        [1., 0., 1., 1., 1.],
        [1., 1., 0., 0., 1.],
        [1., 0., 1., 0., 0.]])

In [27]:
print(C + D.int())
print((C + D.int()).dtype)

tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 0.],
        [1., 0., 1., 1., 1.],
        [1., 1., 0., 0., 1.],
        [1., 0., 1., 0., 0.]])
torch.float32


In [ ]:
torch.set_default_tensor_type('torch.FloatTensor')   #Para que por defecto al hacer operaciones los tensores den flotantes

---
# Tensores de CPU a TPU
---

In [28]:
C.device 

device(type='cpu')

Anteriormente se obsdervó que está coriendo en CPU, ahora identifiquemos si está habilitada la TPU

In [29]:
torch.cuda.is_available()

False

Por el momento la TPU no está disponible, luego hay que configurar el notebook **(entorno de ejecucion)>>(TPU)**

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [3]:
x = torch.randn(3,5) #cpu
y = torch.ones_like(x, device=device) #gpu

In [4]:
x = x.to(device) #gpu

In [5]:
z = x + y

In [6]:
print(z)
print(z.cpu())

tensor([[ 1.7046,  2.9763,  2.4388,  2.0839, -0.4496],
        [-0.1800,  0.0769, -0.3804,  2.5077,  0.7124],
        [ 1.6097,  2.3661,  0.4185,  2.1999, -0.2286]], device='cuda:0')
tensor([[ 1.7046,  2.9763,  2.4388,  2.0839, -0.4496],
        [-0.1800,  0.0769, -0.3804,  2.5077,  0.7124],
        [ 1.6097,  2.3661,  0.4185,  2.1999, -0.2286]])


## Importando dataSet de Pytorch

In [7]:
from torchvision import datasets   #torchvision trae muchos datasets para usar

In [8]:
dir(datasets)

['CIFAR10',
 'CIFAR100',
 'Caltech101',
 'Caltech256',
 'CelebA',
 'Cityscapes',
 'CocoCaptions',
 'CocoDetection',
 'DatasetFolder',
 'EMNIST',
 'FakeData',
 'FashionMNIST',
 'Flickr30k',
 'Flickr8k',
 'HMDB51',
 'ImageFolder',
 'ImageNet',
 'KMNIST',
 'Kinetics400',
 'LSUN',
 'LSUNClass',
 'MNIST',
 'Omniglot',
 'PhotoTour',
 'Places365',
 'QMNIST',
 'SBDataset',
 'SBU',
 'SEMEION',
 'STL10',
 'SVHN',
 'UCF101',
 'USPS',
 'VOCDetection',
 'VOCSegmentation',
 'VisionDataset',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'caltech',
 'celeba',
 'cifar',
 'cityscapes',
 'coco',
 'fakedata',
 'flickr',
 'folder',
 'hmdb51',
 'imagenet',
 'kinetics',
 'lsun',
 'mnist',
 'omniglot',
 'phototour',
 'places365',
 'sbd',
 'sbu',
 'semeion',
 'stl10',
 'svhn',
 'ucf101',
 'usps',
 'utils',
 'video_utils',
 'vision',
 'voc']

In [9]:
cifar = datasets.CIFAR10('/content/drive/My Drive/Colab Notebooks/dl-pytorch/datasets', download=True)

Extracting /content/drive/My Drive/Colab Notebooks/dl-pytorch/datasets/cifar-10-python.tar.gz to /content/drive/My Drive/Colab Notebooks/dl-pytorch/datasets


In [10]:
len(cifar)

50000

In [13]:
cifar.data

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [11]:
data = torch.Tensor(cifar.data)

In [14]:
data

tensor([[[[ 59.,  62.,  63.],
          [ 43.,  46.,  45.],
          [ 50.,  48.,  43.],
          ...,
          [158., 132., 108.],
          [152., 125., 102.],
          [148., 124., 103.]],

         [[ 16.,  20.,  20.],
          [  0.,   0.,   0.],
          [ 18.,   8.,   0.],
          ...,
          [123.,  88.,  55.],
          [119.,  83.,  50.],
          [122.,  87.,  57.]],

         [[ 25.,  24.,  21.],
          [ 16.,   7.,   0.],
          [ 49.,  27.,   8.],
          ...,
          [118.,  84.,  50.],
          [120.,  84.,  50.],
          [109.,  73.,  42.]],

         ...,

         [[208., 170.,  96.],
          [201., 153.,  34.],
          [198., 161.,  26.],
          ...,
          [160., 133.,  70.],
          [ 56.,  31.,   7.],
          [ 53.,  34.,  20.]],

         [[180., 139.,  96.],
          [173., 123.,  42.],
          [186., 144.,  30.],
          ...,
          [184., 148.,  94.],
          [ 97.,  62.,  34.],
          [ 83.,  53.,  34.]],



In [12]:
data.size()

torch.Size([50000, 32, 32, 3])